version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
# Users can use the following import directory to add additional
# configuration to containerd. The imports do not behave exactly like overrides.
# see: https://github.com/containerd/containerd/blob/main/docs/man/containerd-config.toml.5.md#format
imports = ["/etc/containerd/config.d/*.toml"]

[grpc]
address = "/run/containerd/containerd.sock"

[plugins]
[plugins."io.containerd.grpc.v1.cri".containerd]
default_runtime_name = "{{.RuntimeName}}"
discard_unpacked_layers = true

[plugins."io.containerd.grpc.v1.cri"]
sandbox_image = "{{.SandboxImage}}"
enable_cdi = {{.EnableCDI}}

[plugins."io.containerd.grpc.v1.cri".registry]
config_path = "/etc/containerd/certs.d:/etc/docker/certs.d"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.{{.RuntimeName}}]
runtime_type = "io.containerd.runc.v2"
base_runtime_spec = "/etc/containerd/base-runtime-spec.json"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.{{.RuntimeName}}.options]
BinaryName = "{{.RuntimeBinaryName}}"
SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri".cni]
bin_dir = "/opt/cni/bin"
conf_dir = "/etc/cni/net.d"

# TODO: MERGE - check if this works correctly since it's now a template i.e. {{.RuntimeName}}
# Original:
# [plugins]
#  [plugins."io.containerd.grpc.v1.cri".containerd]
#    default_runtime_name = "runc"
#    discard_unpacked_layers = true
#  [plugins."io.containerd.grpc.v1.cri"]
#    sandbox_image = "{{.SandboxImage}}"
#  [plugins."io.containerd.grpc.v1.cri".registry]
#    config_path = "/etc/containerd/certs.d:/etc/docker/certs.d"
#  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
#    runtime_type = "io.containerd.runc.v2"
#  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
#    SystemdCgroup = true
#  [plugins."io.containerd.grpc.v1.cri".cni]
#    bin_dir = "/opt/cni/bin"
#    conf_dir = "/etc/cni/net.d"